# Cask directory for applications
cask_args appdir: "/Applications"

# Taps
tap "homebrew/cask"
# or (maybe):
# tap "homebrew/cask", args: ["--full"]
#tap "homebrew/cask-fonts" # not used below
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/core"

#cask "java8"
#brew "scala"
#brew "sbt"
#brew "maven"
brew "gradle"
brew "gdub"
brew "groovysdk"
brew "node"
brew "graphviz"
cask "intellij-idea"
#cask "intellij-idea-ce"
#cask "sourcetree" # how did sourcetree become so buggy? :'(
#cask "gitkraken"
cask "kdiff3"
#cask "dash"
#cask "dbeaver-community"
cask "docker"
cask "kitematic"
cask "postman"

#cask "kafka-tool"
brew "awscli"
brew "amazon-ecs-cli"
cask "tunnelblick"

#brew "carthage"
#brew "watchman"
#cask "android-file-transfer"
#cask "android-studio"
#cask "drawio"
#cask "nordic-nrf5x-command-line-tools"
#cask "segger-jlink"

#cask "toggl"
cask "rocket-chat"
cask "firefox"

brew "jq"
brew "git-flow"

#mas "Xcode", id: 497799835
mas "Slack", id: 803453959
