alias gd='git diff'
alias gdc='git diff --cached'
alias gh='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
alias go='git checkout'
alias gs='git status'
alias gci='git checkout -- .idea'
