# Cask directory for applications
cask_args appdir: "/Applications"

cask "adobe-creative-cloud"
cask "calibre"
#cask "microsoft-office"
#cask "microsoft-word"
#cask "microsoft-excel"
#cask "microsoft-powerpoint"
mas "Paprika Recipe Manager 3", id: 1303222628
#cask "powerphotos"
