# Cask directory for applications
cask_args appdir: "/Applications"

cask "adobe-creative-cloud"
cask "calibre"
cask "keyboardcleantool"
#cask "microsoft-office"
#cask "microsoft-word"
#cask "microsoft-excel"
#cask "microsoft-powerpoint"
#cask "powerphotos"
