# Cask directory for applications
cask_args appdir: "/Applications"

# Taps
tap "homebrew/cask"
# or (maybe):
# tap "homebrew/cask", args: ["--full"]
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/core"

# Dependencies
brew "mas"

# Shells
brew "zsh"
brew "bash"

# CLI
brew "coreutils"
brew "findutils"
brew "git"
brew "htop"
brew "mtr"
brew "par2"
brew "rclone"
brew "telnet"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"

# Fonts
#cask "font-hack-nerd-font"
#cask "font-source-code-pro"

# GUI applications
cask "1password"
#cask "dropbox" # disable until M1 support is available, use maestral instead
cask "google-chrome"
cask "gpg-suite"
cask "iina"
cask "istat-menus"
cask "iterm2"
cask "keka"
cask "macpar-deluxe"
cask "maestral" # replaces dropbox, until dropbox finally adds M1 support
cask "rectangle"
casl "spotify"
cask "sublime-text"
cask "sublime-merge"

# MAS applications
#mas "Adze Lite", id: 499527341
#mas "Amphetamine", id: 937984704
mas "DaisyDisk", id: 411643860
mas "Flycut", id: 442160987
mas "Hidden Bar", id: 1452453066
mas "Slack", id: 803453959
mas "Todoist", id: 585829637
mas "Notability", id: 360593530
#mas "Trello", id: 1278508951
