# Cask directory for applications
cask_args appdir: "/Applications"

# Taps
tap "homebrew/cask"
# or (maybe):
# tap "homebrew/cask", args: ["--full"]
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/core"

# Dependencies
brew "mas"

# Shells
brew "zsh"
brew "bash"

# CLI
brew "coreutils"
brew "findutils"
brew "git"
brew "htop"
brew "mtr"
brew "par2"
brew "rclone"
brew "telnet"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"

# Fonts
cask "font-hack-nerd-font"
cask "font-source-code-pro"

# GUI applications
cask "1password"
cask "bartender"
cask "dropbox"
cask "google-chrome"
cask "gpg-suite"
cask "iina"
cask "istat-menus"
cask "iterm2"
cask "macpar-deluxe"
cask "rclone-browser"
cask "sizeup"
cask "spotify"
cask "sublime-text"
cask "the-unarchiver"

# disabled
# cask "adobe-photoshop-lightroom"
# cask "firefox"
# cask "flash-player"
# cask "franz"
# cask "macvim"
# cask "sequel-pro"
# cask "skitch"
# cask "silverlight"
# cask "skype"
# cask "jadengeller-helium"
# cask "journey"
# cask "microsoft-office"
# cask "apptivate"
# cask "atom"
# cask "authy"
# cask "caffeine"
# cask "forklift"
# cask "tripmode"
#cask virtualbox # loads kernel module, TODO figure out how to do this nicely automatically

# MAS applications
#mas "Adze Lite", id: 499527341
mas "Amphetamine", id: 937984704
mas "DaisyDisk", id: 411643860
mas "Flycut", id: 442160987
mas "Slack", id: 803453959
mas "Trello", id: 1278508951
